### ISSUE TITLE
{if can_access_cp} always evaluates true

### ISSUE THREAD

**Issue by kevinsmith** [caddis/helpvars#1]
This is probably true for the others as well, but `{if can_access_cp}` as recommended in the docs always evaluates true because `{can_access_cp}` renders as either `y` or `n`. The right conditional here would be `{if can_access_cp == 'y'}`.

**Comment by leigeber** [comment]
Nice catch, that should be the only tag not returning a proper boolean. I've updated the documentation to reflect this.
